### ISSUE TITLE
Figure Issue

### ISSUE THREAD

**Issue by chlocou** [chlocou/dsn1675-planet-website#1]
Hello @thomasjbradley! I am having major troubles getting the last two figure elements on the index page side by side for the medium screen size. I have tried everything I can and I have inspected the element many times. Although the figure element does not have any padding or margin, there seems to be an issue regarding the actual size of it because the blue box that shows the actual size it is taking up on the site is much bigger than what it should be.

**Comment by thomasjbradley** [comment]
The problem is just that since they all want to be on the same line, they all need to be inside the same `.grid`. The code will end up looking something like this:

```html
<div class="grid">
  <div class="unit">
    <figure></figure>
  </div>
  <div class="unit">
    <figure></figure>
  </div>
  <div class="unit">
    <figure></figure>
  </div>
</div>
```
