### ISSUE TITLE
Border Issue

### ISSUE THREAD

**Issue by chlocou** [chlocou/dsn1675-planet-website#2]
Hello @thomasjbradley, I can't seem to be able to get rid of this annoying black border that shows up when you click the masthead's navigation links. I have gone into my css to target the navigation a's and the navigation li's with border: 0 but that seems to have not changed anything.

**Comment by thomasjbradley** [comment]
It's part of the Accessibility module and it's extremely important for keyboard navigation—so don't get rid of it. It's there because we didn't shut off the accessibility code module in Modulifier.

We'll be discussing it in a couple weeks when we talk about accessibility.

**Comment by chlocou** [comment]
Oh I see. Thanks so much for your help Thomas!
